version: '3.7'
services:
  plataformagt-minio:
    image: minio/minio
    container_name: plataformagt-minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9011:9000"
    command: server /data
    networks:
      - plataformagt-network

  plataformagt-keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: plataformagt-keycloak
    command: 'start-dev'
    environment:
      TZ: America/Belem
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://plataformagt-postgresql/keycloak
      KC_DB_USERNAME: appgt
      KC_DB_PASSWORD: plataformagt
      KC_HOSTNAME_URL: http://localhost:9080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: plataformagt
    ports:
      - "9080:8080"
    networks:
      - plataformagt-network

  plataformagt-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: plataformagt-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - plataformagt-network

  plataformagt-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: plataformagt-kafka
    depends_on:
      - plataformagt-zookeeper
    ports:
      - "29092:29092"
    networks:
      - plataformagt-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: plataformagt-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://plataformagt-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  plataformagt-network:
    driver: bridge
    name: plataformagt-network

volumes:
  volume-redis:
    driver: local